clone_folder: c:\AADDotNetLib

install:
- ps: .\InstallAndroidSDK.ps1

image: Visual Studio 2017

configuration: Release

environment:
  JavaSdkDirectory: '%JAVA_HOME%'

before_build:
  - nuget restore ADAL.NET.NoWinRT.sln
  - '"C:/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.6.1 Tools/sn.exe" -Vr *,31bf3856ad364e35'

build:
  project: ADAL.NET.NoWinRT.sln

skip_commits:
  files:
    - '**/*.md'
    - 'changelog.txt'

on_finish:
# Uncomment this to be able to RDP into the build agent
# ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
